# Generated by Django 3.2.7 on 2021-10-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211026_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='description',
            field=models.TextField(default='Не описано.'),
        ),
        migrations.AddField(
            model_name='statement',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
