# Generated by Django 3.2.7 on 2021-10-26 15:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211026_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Користувач', 'Користувач'), ('Журналист', 'Журналист')], default='Користувач', max_length=20),
        ),
    ]
