# Generated by Django 3.2.7 on 2021-10-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unconfirmed_discord',
        ),
    ]
